webtalk_init -webtalk_dir C:/Users/tunak/Google Drive/School/Current Courses/EEE102/Project/project_file/game_of_life/game_of_life.sim/sim_1/behav/xsim/xsim.dir/environment_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Dec 26 02:53:48 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9ecbd3485d4a5925bb2549001b53d7d4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "49e95c6540cd4677bd23ffe98e8f2640" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "60" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5600_KB" -context "xsim\\usage"
webtalk_transmit -clientid 494020756 -regid "" -xml C:/Users/tunak/Google Drive/School/Current Courses/EEE102/Project/project_file/game_of_life/game_of_life.sim/sim_1/behav/xsim/xsim.dir/environment_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/tunak/Google Drive/School/Current Courses/EEE102/Project/project_file/game_of_life/game_of_life.sim/sim_1/behav/xsim/xsim.dir/environment_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/tunak/Google Drive/School/Current Courses/EEE102/Project/project_file/game_of_life/game_of_life.sim/sim_1/behav/xsim/xsim.dir/environment_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
