# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk100mhz]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk100mhz]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk100mhz]
 
# Switches
set_property PACKAGE_PIN V17 [get_ports {enable}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {enable}]
set_property PACKAGE_PIN V16 [get_ports {initial_condition[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {initial_condition[0]}]
set_property PACKAGE_PIN W16 [get_ports {initial_condition[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {initial_condition[1]}]
set_property PACKAGE_PIN W17 [get_ports {initial_condition[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {initial_condition[2]}]
#set_property PACKAGE_PIN W15 [get_ports {sw[4]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
#set_property PACKAGE_PIN V15 [get_ports {button[0]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {button[0]}]
#set_property PACKAGE_PIN W14 [get_ports {sw[6]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
#set_property PACKAGE_PIN W13 [get_ports {sw[7]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
#set_property PACKAGE_PIN V2 [get_ports {sw[8]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[8]}]
#set_property PACKAGE_PIN T3 [get_ports {sw[9]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[9]}]
set_property PACKAGE_PIN T2 [get_ports {size_selection[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {size_selection[0]}]
set_property PACKAGE_PIN R3 [get_ports {size_selection[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {size_selection[1]}]
#set_property PACKAGE_PIN W2 [get_ports {time_selection[3]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {time_selection[3]}]
#set_property PACKAGE_PIN U1 [get_ports {time_selection[2]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {time_selection[2]}]
set_property PACKAGE_PIN T1 [get_ports {time_selection[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {time_selection[0]}]
set_property PACKAGE_PIN R2 [get_ports {time_selection[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {time_selection[1]}]
 

# LEDs
set_property PACKAGE_PIN U16 [get_ports {leds[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]
set_property PACKAGE_PIN E19 [get_ports {leds[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property PACKAGE_PIN U19 [get_ports {leds[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]
set_property PACKAGE_PIN V19 [get_ports {leds[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[3]}]
#set_property PACKAGE_PIN W18 [get_ports {out_row2[3]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {out_row2[3]}]
#set_property PACKAGE_PIN U15 [get_ports {out_row2[2]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {out_row2[2]}]
#set_property PACKAGE_PIN U14 [get_ports {out_row2[1]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {out_row2[1]}]
#set_property PACKAGE_PIN V14 [get_ports {out_row2[0]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {out_row2[0]}]
#set_property PACKAGE_PIN V13 [get_ports {out_row1[3]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {out_row1[3]}]
#set_property PACKAGE_PIN V3 [get_ports {out_row1[2]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {out_row1[2]}]
set_property PACKAGE_PIN W3 [get_ports {leds[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[4]}]
set_property PACKAGE_PIN U3 [get_ports {leds[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[5]}]
#set_property PACKAGE_PIN P3 [get_ports {out_row0[3]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {out_row0[3]}]
#set_property PACKAGE_PIN N3 [get_ports {out_row0[2]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {out_row0[2]}]
set_property PACKAGE_PIN P1 [get_ports {leds[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[6]}]
set_property PACKAGE_PIN L1 [get_ports {leds[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leds[7]}]
	
	
#Buttons
set_property PACKAGE_PIN U18 [get_ports button[0]]						
	set_property IOSTANDARD LVCMOS33 [get_ports button[0]]
set_property PACKAGE_PIN T18 [get_ports button[1]]						
	set_property IOSTANDARD LVCMOS33 [get_ports button[1]]
set_property PACKAGE_PIN W19 [get_ports button[2]]						
	set_property IOSTANDARD LVCMOS33 [get_ports button[2]]
set_property PACKAGE_PIN T17 [get_ports button[3]]						
	set_property IOSTANDARD LVCMOS33 [get_ports button[3]]
set_property PACKAGE_PIN U17 [get_ports button[4]]						
	set_property IOSTANDARD LVCMOS33 [get_ports button[4]]	
	
##VGA Connector
    set_property PACKAGE_PIN G19 [get_ports {vgaRed[0]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[0]}]
    set_property PACKAGE_PIN H19 [get_ports {vgaRed[1]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[1]}]
    set_property PACKAGE_PIN J19 [get_ports {vgaRed[2]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[2]}]
    set_property PACKAGE_PIN N19 [get_ports {vgaRed[3]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[3]}]
    set_property PACKAGE_PIN N18 [get_ports {vgaBlue[0]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[0]}]
    set_property PACKAGE_PIN L18 [get_ports {vgaBlue[1]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[1]}]
    set_property PACKAGE_PIN K18 [get_ports {vgaBlue[2]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[2]}]
    set_property PACKAGE_PIN J18 [get_ports {vgaBlue[3]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[3]}]
    set_property PACKAGE_PIN J17 [get_ports {vgaGreen[0]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[0]}]
    set_property PACKAGE_PIN H17 [get_ports {vgaGreen[1]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[1]}]
    set_property PACKAGE_PIN G17 [get_ports {vgaGreen[2]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[2]}]
    set_property PACKAGE_PIN D17 [get_ports {vgaGreen[3]}]                
        set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[3]}]
    set_property PACKAGE_PIN P19 [get_ports horizontal_sync]                        
        set_property IOSTANDARD LVCMOS33 [get_ports horizontal_sync]
    set_property PACKAGE_PIN R19 [get_ports vertical_sync]                        
        set_property IOSTANDARD LVCMOS33 [get_ports vertical_sync]


